import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./component/Nav";
import LowerBanner from "./component/LowerBanner";
import Top from "./component/Top";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Top></Top>
        <Nav></Nav>
        
        {children}
      </body>
    </html>
  );
}
