import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./component/Nav";
import Top from "./component/Top";
import Splash from "./component/Splash";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const ANNOUNCEMENTS = [
    "Black Friday: 10% off storewide",
    "Free shipping on orders above $75",
    "Vegan • Cruelty‑free • Clean beauty",
    "New arrivals in skincare & haircare",
  ]
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Splash />
        <Top props={ANNOUNCEMENTS}></Top>
        <Nav></Nav>
        
        {children}

        <Footer></Footer>
      </body>
    </html>
  );
}
